"""
Runs LLM-generated code and tests inside an isolated Docker container.

The LLM output is untrusted and must never execute directly on the agent's host.
Each run gets a fresh, ephemeral container that is destroyed on exit.

Security constraints applied at runtime:
- No network access (--network none)
- Memory cap: 256 MB
- CPU cap: 0.5 cores
- Hard timeout: 30 s (container is killed if exceeded)
- Read-only volume mount: the host filesystem cannot be modified
"""

import subprocess
import tempfile
import os
import uuid
from dataclasses import dataclass


SANDBOX_IMAGE = "test-agent-sandbox:latest"
DEFAULT_TIMEOUT_SECONDS = 30


@dataclass
class SandboxResult:
    passed: bool
    stdout: str
    stderr: str
    exit_code: int
    timed_out: bool = False


def build_sandbox_image(sandbox_dir: str) -> None:
    """
    Builds the sandbox Docker image.
    Only needs to run once, or when sandbox/requirements.txt changes.
    """
    result = subprocess.run(
        ["docker", "build", "-t", SANDBOX_IMAGE, sandbox_dir],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Failed to build sandbox image:\n{result.stderr}")


def run_test_in_sandbox(
    source_code: str,
    test_code: str,
    module_name: str = "target_module",
    timeout_seconds: int = DEFAULT_TIMEOUT_SECONDS,
) -> SandboxResult:
    """
    Runs a generated test against source code inside an isolated container.

    Args:
        source_code: the original function/module being tested.
        test_code: the pytest test generated by the LLM (must import module_name).
        module_name: the filename stem given to the source code file.
        timeout_seconds: hard kill limit before the container is stopped.

    Returns:
        SandboxResult with pass/fail, stdout, stderr, and timeout flag.
    """
    run_id = uuid.uuid4().hex[:8]

    with tempfile.TemporaryDirectory(prefix=f"sandbox_{run_id}_") as tmp_dir:
        source_path = os.path.join(tmp_dir, f"{module_name}.py")
        test_path = os.path.join(tmp_dir, f"test_{module_name}.py")

        with open(source_path, "w") as f:
            f.write(source_code)
        with open(test_path, "w") as f:
            f.write(test_code)

        # Normalize to forward slashes for Docker Desktop on Windows
        mount_path = tmp_dir.replace("\\", "/")
        container_name = f"sandbox-run-{run_id}"

        cmd = [
            "docker", "run",
            "--rm",
            "--name", container_name,
            "--network", "none",
            "--memory", "256m",
            "--cpus", "0.5",
            "-v", f"{mount_path}:/sandbox/work:ro",
            "-w", "/sandbox/work",
            SANDBOX_IMAGE,
            "pytest", "--tb=short", "-v", "-p", "no:cacheprovider",
            f"test_{module_name}.py",
        ]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout_seconds,
            )
            return SandboxResult(
                passed=result.returncode == 0,
                stdout=result.stdout,
                stderr=result.stderr,
                exit_code=result.returncode,
            )
        except subprocess.TimeoutExpired:
            subprocess.run(["docker", "kill", container_name], capture_output=True)
            return SandboxResult(
                passed=False,
                stdout="",
                stderr=f"Execution cancelled: exceeded the {timeout_seconds}s limit",
                exit_code=-1,
                timed_out=True,
            )
